#!/bin/sh
param=""
if [ $# -ne 1 ]; then
	param="死";
else
	param=$1;
fi

append_header=" 人人"
append_footer="^Y^Y"
header="＿人人"
footer="￣Y^Y^Y^"
count=1
size=`printf "${param}" | wc -c`
size=`expr $size / 2`
size=`expr $size - 1`
while [ $count -le $size ];
do
	header="${header}${append_header}"
	footer="${footer}${append_footer}"
	count=`expr $count + 3`
done

header="${header} 人人＿"
footer="${footer}Y^Y￣"

echo "${header}"
echo "＞ 突然の${param} ＜"
echo "${footer}"

exit 0

